### ISSUE TITLE
Minecraft 1.12 Support

### ISSUE THREAD

**Issue by kitzu** [itzg/dockerfiles#162]
1.12 (also Spigot 1.12 with BUILD_FROM_SOURCE=true) will always end with a JsonParseException:
`[19:21:05 ERROR]: Encountered an unexpected exception
com.google.gson.JsonParseException: java.io.EOFException: End of input at line 2 column 1 path $
	at net.minecraft.server.v1_12_R1.ChatDeserializer.a(SourceFile:506) ~[spigot_server.jar:git-Spigot-cd6ba67-f7d14f1]
	at net.minecraft.server.v1_12_R1.ChatDeserializer.a(SourceFile:522) ~[spigot_server.jar:git-Spigot-cd6ba67-f7d14f1]
	at net.minecraft.server.v1_12_R1.JsonList.load(JsonList.java:174) ~[spigot_server.jar:git-Spigot-cd6ba67-f7d14f1]
	at net.minecraft.server.v1_12_R1.DedicatedPlayerList.A(SourceFile:99) ~[spigot_server.jar:git-Spigot-cd6ba67-f7d14f1]
	at net.minecraft.server.v1_12_R1.DedicatedPlayerList.<init>(SourceFile:25) ~[spigot_server.jar:git-Spigot-cd6ba67-f7d14f1]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:183) ~[spigot_server.jar:git-Spigot-cd6ba67-f7d14f1]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot_server.jar:git-Spigot-cd6ba67-f7d14f1]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.io.EOFException: End of input at line 2 column 1 path $
	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1393) ~[spigot_server.jar:git-Spigot-cd6ba67-f7d14f1]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:549) ~[spigot_server.jar:git-Spigot-cd6ba67-f7d14f1]
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:425) ~[spigot_server.jar:git-Spigot-cd6ba67-f7d14f1]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:74) ~[spigot_server.jar:git-Spigot-cd6ba67-f7d14f1]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61) ~[spigot_server.jar:git-Spigot-cd6ba67-f7d14f1]
	at net.minecraft.server.v1_12_R1.ChatDeserializer.a(SourceFile:504) ~[spigot_server.jar:git-Spigot-cd6ba67-f7d14f1]
	... 7 more
[19:21:05 ERROR]: 	Cause of unexpected exception was
java.io.EOFException: End of input at line 2 column 1 path $
	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1393) ~[spigot_server.jar:git-Spigot-cd6ba67-f7d14f1]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:549) ~[spigot_server.jar:git-Spigot-cd6ba67-f7d14f1]
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:425) ~[spigot_server.jar:git-Spigot-cd6ba67-f7d14f1]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:74) ~[spigot_server.jar:git-Spigot-cd6ba67-f7d14f1]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61) ~[spigot_server.jar:git-Spigot-cd6ba67-f7d14f1]
	at net.minecraft.server.v1_12_R1.ChatDeserializer.a(SourceFile:504) ~[spigot_server.jar:git-Spigot-cd6ba67-f7d14f1]
	at net.minecraft.server.v1_12_R1.ChatDeserializer.a(SourceFile:522) ~[spigot_server.jar:git-Spigot-cd6ba67-f7d14f1]
	at net.minecraft.server.v1_12_R1.JsonList.load(JsonList.java:174) ~[spigot_server.jar:git-Spigot-cd6ba67-f7d14f1]
	at net.minecraft.server.v1_12_R1.DedicatedPlayerList.A(SourceFile:99) ~[spigot_server.jar:git-Spigot-cd6ba67-f7d14f1]
	at net.minecraft.server.v1_12_R1.DedicatedPlayerList.<init>(SourceFile:25) ~[spigot_server.jar:git-Spigot-cd6ba67-f7d14f1]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:183) ~[spigot_server.jar:git-Spigot-cd6ba67-f7d14f1]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot_server.jar:git-Spigot-cd6ba67-f7d14f1]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[19:21:05 ERROR]: This crash report has been saved to: /data/./crash-reports/crash-2017-06-14_19.21.05-server.txt
[19:21:05 INFO]: Stopping server`

**Comment by itzg** [comment]
I had to make this fix for vanilla 1.12

https://github.com/itzg/dockerfiles/commit/e509563b109695a61d1bf43b6a5fa0c9440e37f6#diff-1b75c648f95c688de936b9c07a9b0008

I'll look if something additional is needed down the Spigot path.

**Comment by matthewguenther** [comment]
I am having a similar issue using a QNAP NAS with a docker compatible container station. Upon first launch of a new container I see this in console. 1.11.2 worked perfectly.

`[20:47:19] [Server thread/INFO]: Stopping server   `                                                                                                                                                                     
`Switching to user 'minecraft' `                                                                                                                                                                                          
`Checking version information.          `                                                                                                                                                                                 
`Checking type information.  `                                                                                                                                                                                            
`Setting initial memory to 1G and max to 1G   `                                                                                                                                                                           
`+ [[ VANILLA == \F\E\E\D\-\T\H\E\-\B\E\A\S\T ]]           `                                                                                                                                                              
`+ '[' -f /data/bootstrap.txt ']'    `                                                                                                                                                                                    
`+ exec java -XX:+UseG1GC -Xms1G -Xmx1G -jar minecraft_server.1.12.jar   `                                                                                                                                                
`[20:48:20] [Server thread/INFO]: Starting minecraft server version 1.12    `                                                                                                                                             
`[20:48:20] [Server thread/INFO]: Loading properties    `                                                                                                                                                                 
`[20:48:20] [Server thread/INFO]: Default game type: SURVIVAL      `                                                                                                                                                      
`[20:48:20] [Server thread/INFO]: Generating keypair            `                                                                                                                                                         
`[20:48:21] [Server thread/INFO]: Starting Minecraft server on *:25565   `                                                                                                                                                
`[20:48:21] [Server thread/INFO]: Using default channel type   `                                                                                                                                                          
`[20:48:21] [Server thread/ERROR]: Encountered an unexpected exception      `                                                                                                                                             
`com.google.gson.JsonParseException: java.io.EOFException: End of input at line 2 column 1 path $    `                                                                                                                    
  `      at ra.a(SourceFile:506) ~[minecraft_server.1.12.jar:?]                              `                                                                                                                            
    `    at ra.a(SourceFile:522) ~[minecraft_server.1.12.jar:?]               `                                                                                                                                           
    `    at pn.g(SourceFile:141) ~[minecraft_server.1.12.jar:?]           `                                                                                                                                               
    `    at nw.A(SourceFile:99) ~[minecraft_server.1.12.jar:?]          `                                                                                                                                                 
    `    at nw.<init>(SourceFile:25) ~[minecraft_server.1.12.jar:?]    `                                                                                                                                                  
    `    at nx.j(SourceFile:188) ~[minecraft_server.1.12.jar:?]        `                                                                                                                                                  
    `    at net.minecraft.server.MinecraftServer.run(SourceFile:434) [minecraft_server.1.12.jar:?]   `                                                                                                                    
    `    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]            `                                                                                                                                              
`Caused by: java.io.EOFException: End of input at line 2 column 1 path $              `                                                                                                                                   
 `       at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1393) ~[minecraft_server.1.12.jar:?]         `                                                                                            
   `     at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:549) ~[minecraft_server.1.12.jar:?]           `                                                                                                      
     `   at com.google.gson.stream.JsonReader.peek(JsonReader.java:425) ~[minecraft_server.1.12.jar:?]`                                                                                                                   
    `    at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:74) ~[minecraft_server.1.12.jar:?]                                 `                                
      `  at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61) ~[minecraft_server.1.12.jar:?]         `                                                        
    `    at ra.a(SourceFile:504) ~[minecraft_server.1.12.jar:?]                    `                                                                                                                                      
       ` ... 7 more          `                                                                                                                                                                                            
`[20:48:21] [Server thread/ERROR]: This crash report has been saved to: /data/./crash-reports/crash-2017-06-17_20.48.21-server.txt       `                                                                                
`[20:48:21] [Server thread/INFO]: Stopping server  `                                                                                                                                                                      
`[20:48:21] [Server Shutdown Thread/INFO]: Stopping server`

**Comment by itzg** [comment]
@matthewguenther at least in your case it appears to be retaining the prior `/data` content, specifically the "malformed" JSON files. Starting a new container purposely with no attached volume, I can see the additional startup messages I would expect, such as "Creating server.properties" (below). One way to solve this is to `docker exec mc rm banned-players.json banned-ips.json` into the container and then on the next container start it'll re-initialize those files.

```
> docker run -it --rm -p 25565:25565 -e EULA=TRUE itzg/minecraft-server
Switching to user 'minecraft'
Checking version information.
Checking type information.
Downloading minecraft_server.1.12.jar ...
Creating server.properties
Setting motd to A Minecraft Server Powered by Docker
Setting enable-rcon to true
Setting rcon.password to minecraft
Setting rcon.port to 25575
Setting level-name to world
Setting pvp to true
Setting online-mode to TRUE
Setting level type to DEFAULT
Setting difficulty to 1
Setting initial memory to 1G and max to 1G
[22:16:51] [Server thread/INFO]: Starting minecraft server version 1.12
[22:16:51] [Server thread/INFO]: Loading properties
[22:16:51] [Server thread/INFO]: Default game type: SURVIVAL
[22:16:51] [Server thread/INFO]: Generating keypair
[22:16:51] [Server thread/INFO]: Starting Minecraft server on *:25565
[22:16:51] [Server thread/INFO]: Using epoll channel type
[22:16:51] [Server thread/INFO]: Preparing level "world"
[22:16:53] [Server thread/INFO]: Loaded 488 advancements
[22:16:54] [Server thread/INFO]: Preparing start region for level 0
[22:16:55] [Server thread/INFO]: Preparing spawn area: 5%
[22:16:56] [Server thread/INFO]: Preparing spawn area: 8%
[22:16:57] [Server thread/INFO]: Preparing spawn area: 13%
[22:16:58] [Server thread/INFO]: Preparing spawn area: 17%
[22:16:59] [Server thread/INFO]: Preparing spawn area: 22%
[22:17:00] [Server thread/INFO]: Preparing spawn area: 28%
[22:17:01] [Server thread/INFO]: Preparing spawn area: 34%
[22:17:02] [Server thread/INFO]: Preparing spawn area: 40%
[22:17:03] [Server thread/INFO]: Preparing spawn area: 44%
[22:17:04] [Server thread/INFO]: Preparing spawn area: 48%
[22:17:05] [Server thread/INFO]: Preparing spawn area: 48%
[22:17:06] [Server thread/INFO]: Preparing spawn area: 52%
[22:17:07] [Server thread/INFO]: Preparing spawn area: 58%
[22:17:08] [Server thread/INFO]: Preparing spawn area: 65%
[22:17:09] [Server thread/INFO]: Preparing spawn area: 72%
[22:17:10] [Server thread/INFO]: Preparing spawn area: 80%
[22:17:11] [Server thread/INFO]: Preparing spawn area: 84%
[22:17:12] [Server thread/INFO]: Preparing spawn area: 89%
[22:17:13] [Server thread/INFO]: Preparing spawn area: 92%
[22:17:15] [Server thread/INFO]: Preparing spawn area: 97%
[22:17:15] [Server thread/INFO]: Done (23.649s)! For help, type "help" or "?"
[22:17:15] [Server thread/INFO]: Starting remote control listener
[22:17:15] [RCON Listener #1/INFO]: RCON running on 0.0.0.0:25575
```

**Comment by matthewguenther** [comment]
My particular server does not have a command like for boot arguments, how would I go about this using the file system?

**Comment by itzg** [comment]
@matthewguenther hmm, that's hard to say since I'm used to direct access to the `docker` CLI. The alternative, that is likely easier, is to double check that a new 1.12 container is using a distinct volume attachment for `/data`.

**Comment by dereekb** [comment]
I ran into this issue earlier when starting a new container in a new folder. Wouldn't start properly until I copied over the .json configurations from a previous save.

`[20:15:14] [Server thread/INFO]: Starting minecraft server version 1.12
[20:15:14] [Server thread/INFO]: Loading properties
[20:15:14] [Server thread/INFO]: Default game type: SURVIVAL
[20:15:14] [Server thread/INFO]: Generating keypair
[20:15:14] [Server thread/INFO]: Starting Minecraft server on *:25565
[20:15:14] [Server thread/INFO]: Using epoll channel type
[20:15:15] [Server thread/ERROR]: Encountered an unexpected exception
com.google.gson.JsonParseException: java.io.EOFException: End of input at line 2 column 1 path $
	at ra.a(SourceFile:506) ~[minecraft_server.1.12.jar:?]
	at ra.a(SourceFile:522) ~[minecraft_server.1.12.jar:?]
	at pn.g(SourceFile:141) ~[minecraft_server.1.12.jar:?]
	at nw.A(SourceFile:99) ~[minecraft_server.1.12.jar:?]
	at nw.<init>(SourceFile:25) ~[minecraft_server.1.12.jar:?]
	at nx.j(SourceFile:188) ~[minecraft_server.1.12.jar:?]
	at net.minecraft.server.MinecraftServer.run(SourceFile:434) [minecraft_server.1.12.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
Caused by: java.io.EOFException: End of input at line 2 column 1 path $
	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1393) ~[minecraft_server.1.12.jar:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:549) ~[minecraft_server.1.12.jar:?]
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:425) ~[minecraft_server.1.12.jar:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:74) ~[minecraft_server.1.12.jar:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61) ~[minecraft_server.1.12.jar:?]
	at ra.a(SourceFile:504) ~[minecraft_server.1.12.jar:?]
	... 7 more
[20:15:15] [Server thread/ERROR]: This crash report has been saved to: /data/./crash-reports/crash-2017-07-02_20.15.15-server.txt
[20:15:15] [Server thread/INFO]: Stopping server
[20:15:15] [Server Shutdown Thread/INFO]: Stopping server`

Here's the argument I used to start the container:

`docker run -e 'JVM_OPTS=-Xmx4096M -Xms1024M' -d -v /media/ramdisk/servers/minecraft/v3:/data -p 25565:25565 -e DIFFICULTY=hard -e EULA=TRUE --restart=unless-stopped --name mc_v_l itzg/minecraft-server`

**Comment by itzg** [comment]
@dereekb and @kitzu even though's a manual way to fix up the empty JSON files, I'll work on a start-time fixer-upper in the script. Stay tuned...

**Comment by itzg** [comment]
@dereekb, @kitzu , please do a `pull` of the latest and see if that fix will get your server running.

**Comment by dereekb** [comment]
Worked for me. Started a new container in a new directory without any issues. 👍

**Comment by matthewguenther** [comment]
Just an update from my end after a bit of fiddling. When creating a new container, I still get the same errors and fail to start. The problem does indeed seem to be to be with the JSON files. Currently, my container only creates the following JSON files: `banned-ips`, `banned-players`, and `usercache`. Missing are `ops`, and `whitelist`. Deleting all the JSON from the container and copying over the JSON from a functioning 1.11.2 container fixes the issue.

**Comment by itzg** [comment]
Perhaps I should have the start script scrub all five of those json files.

**Comment by itzg** [comment]
Sorry for the delay on this. I should be able to get to this today or so.

**Comment by itzg** [comment]
I have pushed an update that will check and fix all json files. Give that a try, please.
