### ISSUE TITLE
Feed The Beast Server could not be started

### ISSUE THREAD

**Issue by k1ngf15h3r** [itzg/dockerfiles#212]
Hi man, 

we wrote about the starting issue with FTB Server Modpacks a few weeks ago. Today I tried it again with hosting  FTB Revelation 1.8 but still getting errors about missing classes in the container logs. Server gives following output when trying to start 

```
Switching to user 'minecraft'
Checking version information.
curl: (6) Could not resolve host: launchermeta.mojang.com
Checking type information.
Looking for Feed-The-Beast server modpack.
Installing legacy java fixer to /data/FeedTheBeast/mods/legacyjavafixer.jar
curl: (6) Could not resolve host: ftb.cursecdn.com
server.properties already created, skipping
Setting ops
Skipping JSON check. No files present.
Setting initial memory to 1G and max to 1G
Running FTB server modpack start ...
Starting server
OpenJDK 64-Bit Server VM warning: Using the ParNew young collector with the Serial old collector is deprecated and will likely be removed in a future release
We appear to be missing one or more essential library files.
You will need to add them to your server before FML and Forge will run successfully.java.lang.ClassNotFoundException: net.minecraft.launchwrapper.Launch
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:44)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:31)
```
I run the server on a qnap NAS with `Docker version 1.11.2, build a125cdf`

EDIT: this is my docker start script
```
docker pull itzg/minecraft-server:latest

docker stop mc-revelation
docker rm mc-revelation

docker run --detach --name mc-revelation \
    --publish 0.0.0.0:25565:25565 \
    --publish 0.0.0.0:25575:25575 \
    --restart always \
    -e EULA=TRUE \
    -e TYPE=FTB \
    -e FTB_SERVER_MOD=FTBRevelationServer.zip \
    -e ENABLE_RCON=true \
    -e RCON_PASSWORD=********** \
    -e OPS=k1ngf15h3r \
    -e ENABLE_QUERY=true \
    -e MAX_PLAYERS=10 \
    -e ALLOW_NETHER=true \
    -e ANNOUNCE_PLAYER_ACHIEVEMENTS=true \
    -e ENABLE_COMMAND_BLOCK=true \
    -e FORCE_GAMEMODE=true \
    -e GENERATE_STRUCTURES=true \
    -e HARDCORE=false \
    -e SPAWN_ANIMALS=true \
    -e SPAWN_MONSTERS=true \
    -e SPAWN_NPCS=true \
    -e MODE=survival \
    -e 'MOTD=FTB Revelation 1.8.0 by k1ngf15h3r' \
    -e PVP=false \
    -e ONLINE_MODE=TRUE \
    -e MIN_RAM=1G -e MAX_RAM=4G -e PERMGEN_SIZE=512M \
    -e FTB_LEGACYJAVAFIXER=true \
    --volume /share/Multimedia/mc_revelation:/data \
    itzg/minecraft-server:latest
```

Any ideas how to fix this?

**Comment by k1ngf15h3r** [comment]
I tried to fix and build it locally but without success. I think there will be an issue with `bash` or `sh` and with `curl` in the image

**Comment by itzg** [comment]
It looks like some kind of DNS issue is happening in your case just from lines like

```
curl: (6) Could not resolve host: launchermeta.mojang.com
```

To sanity check, try pinging that host from within the image

```
docker run --rm --entrypoint ping itzg/minecraft-server launchermeta.mojang.com
```

and then try the same from the host running the docker daemon.

**Comment by k1ngf15h3r** [comment]
@itzg disabling IPv6 and changing google dns to cloudflare dns does not resolve the problem

**Comment by k1ngf15h3r** [comment]
@itzg 
maybe this helps, but changed primary and secondary dns to 1.1.1.1 and 1.0.0.1 and there is the same error :-(
```
bash-4.4# cat /etc/resolv.conf
nameserver 192.168.178.1
nameserver 1.1.1.1

bash-4.4# nslookup launchermeta.mojang.com
nslookup: can't resolve '(null)': Name does not resolve

Name:      launchermeta.mojang.com
Address 1: 54.240.162.52 server-54-240-162-52.fra6.r.cloudfront.net

bash-4.4# nslookup ftb.cursecdn.com
nslookup: can't resolve '(null)': Name does not resolve

Name:      ftb.cursecdn.com
Address 1: 52.85.178.190 server-52-85-178-190.fra50.r.cloudfront.net
Address 2: 2600:9000:200d:c00:3:cc9d:3c87:c9c1
Address 3: 2600:9000:200d:1200:3:cc9d:3c87:c9c1
Address 4: 2600:9000:200d:1c00:3:cc9d:3c87:c9c1
Address 5: 2600:9000:200d:2000:3:cc9d:3c87:c9c1
Address 6: 2600:9000:200d:5a00:3:cc9d:3c87:c9c1
Address 7: 2600:9000:200d:7600:3:cc9d:3c87:c9c1
Address 8: 2600:9000:200d:a600:3:cc9d:3c87:c9c1
Address 9: 2600:9000:200d:dc00:3:cc9d:3c87:c9c1
```

**Comment by k1ngf15h3r** [comment]
[SOLVED]
The docker version on my QNAP NAS was buggy and could not connect to the internet from any container. The fact that I only use minecraft server as container on my nas was not helpful to get this information 😆  so I upgraded NAS Firmware and found out that I have to manually update docker through the QNAP App Center. My FTB Revelation Server boots up now and I will craft some magic things ;-)

thanks for helping 👍

**Comment by TrueOsiris** [comment]
I'm astonished that you could use the latest minecraft server version for this.
Shouldn't you pull the one compliant with the FTB server? They're mostly indicating a 1.10.2.

**Comment by itzg** [comment]
@TrueOsiris the `TYPE=FTB` downloads the specified FTB bundle which includes the appropriate minecraft server jar version. Any mention of pulling the "latest version" is just non-FTB messages from the version detection needed for non-FTB server types.
